version: "3.9" # optional since v1.27.0
services:
    server:
        image: nodered/node-red
        container_name: nodered
        ports:
            - "1880:1880"
            - "1883:1883"
        volumes:
            - ./node_red_data:/data
        networks:
            - general
    db:
        image: influxdb
        container_name: influxdb
        ports:
            - "8086:8086"
        volumes:
            - ./influx_data:/var/lib/influxdb2
        networks:
            - general
    ui:
        image: grafana/grafana-oss
        container_name: grafana
        ports:
            - "4000:3000"
        tmpfs:
            - /run
        volumes:
            - ./grafana_data:/var/lib/grafana
        networks:
            - general
        links:
            - db
networks:
    general:
        name: iot-net
        driver: bridge
